name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Load NVM (Node Version Manager) to make npm/node available
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Navigate to the project directory
            cd ~/nginx-with-reverse-proxy

            # Pull latest changes
            git pull origin main

            # Update api-server
            cd api-server
            npm install --production
            pm2 restart api-server || pm2 start main.js --name api-server

            # Update ejs-server
            cd ../ejs-server
            npm install --production
            pm2 restart ejs-server || pm2 start app.js --name ejs-server

            # Save PM2 state
            pm2 save
